### ISSUE TITLE
Add notification settings

### ISSUE THREAD

**Issue by fosterlynn** [opencooperativeecosystem/kanban#1]
In OCP, the notifications are bothering people because you can't turn your own off and on unless you have admin permissions (they have not been added in the work app).

This issue is to add a very simple notification settings page or modal or whatever works best into the profile accessible in the kanban.  (Or perhaps that is a different repo, if so, I'll move the issue.)

The api will need to be also added.

Note: This issue is to do just the simplest way to implement the current notifications.  There could be another issue at some point to make use of the other features of the existing notification app on the backend (like other methods than email, etc.)

**Comment by ivanminutillo** [comment]
I already added a setting page to edit name/email/photo, maybe this issue can be solved in short time if we have the API available...

**Comment by ivanminutillo** [comment]
deployed the new setting page... we can close it :)
