### ISSUE TITLE
Left panel and project panel are off-by-one

### ISSUE THREAD

**Issue by bhaugen** [opencooperativeecosystem/kanban#17]
Or, the left panel has two rows for each project, and only the one with no label is the correct one. The one with a label is for the next project down the list.
Screenshots:
![screenshot from 2018-02-28 08-44-19](https://user-images.githubusercontent.com/117439/36793811-fd434b64-1c63-11e8-81a3-fe3a9bd64bc6.png)
![screenshot from 2018-02-28 08-44-32](https://user-images.githubusercontent.com/117439/36793817-043b522c-1c64-11e8-8f15-4b984a99ff97.png)

**Comment by ivanminutillo** [comment]
this should be fixed with the latest now
