### ISSUE TITLE
Open in New Tab

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/kanban#3]
When you try to open a board in a new tab it shows a "page not found" error.
(am using Firefox Quantum)

**Comment by ivanminutillo** [comment]
true, it is because the app saves the login token in session storage, that is to say, related to the browser tab you are in, much better to use local storage, in this way after you perform the login you can open the app in any other tabs (of the same browser) and be automatically logged.

**Comment by ivanminutillo** [comment]
fixed, thanks
