### ISSUE TITLE
Show page path

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/kanban#5]
It would be useful to show the path of the web site on the top, so when you visit different pages (plans, projects etc.) you could easily trace that and go back if needed. e.g. Circular Economy/1:1 Campaign/Leaflet-to-merchants

**Comment by ivanminutillo** [comment]
Actually there is a sort of breadcrumb on top of each plan page, basically it replicates the trello UX:
Plan Name | Organization Name (with Link)
Eg.
<img width="727" alt="screen shot 2017-12-20 at 11 17 54" src="https://user-images.githubusercontent.com/1852065/34202342-c966a34a-e577-11e7-8b14-a5b055bf5776.png">
